#!/usr/bin/perl

# Usage: relink perlexpr [symlinknames]

($op = shift) || die "Usage: relink perlexpr [filenames]\n";

if (!@ARGV) {
    @ARGV = <STDIN>;
    chop(@ARGV);
}

for (@ARGV) {
    $name = $_;
    $_ = readlink($_);
    next unless defined $_;
    $was = $_;
    eval $op;
    die $@ if $@;
    if ($was ne $_) {
        unlink($name);
        symlink($_, $name);
    }
}
